services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - docker-compose.env

  redis:
    image: redis:7-alpine
    ports:
      - "6383:6379"

  web:
    build: .
    command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8002:8000"
    depends_on:
      - db
      - redis
    env_file:
      - docker-compose.env

volumes:
  postgres_data:
