# Generated by Django 4.2.7 on 2025-10-21 15:13

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('affiliate_encoded_value', models.CharField(db_index=True, max_length=50, unique=True)),
                ('payout_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('conversion_ratio_target', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('conversion_ratio_deviance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('daily_revenue_deviance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('geos', models.JSONField(default=list, help_text='List of country codes')),
                ('sub1_type_generate', models.TextField(help_text="Lambda function as string (e.g., 'lambda: str(random.randint(100000, 999999))')")),
                ('sub2_type_generate', models.TextField(help_text='Lambda function as string (e.g., \'lambda: "".join(random.choices(string.ascii_lowercase + string.digits, k=32))\')')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Affiliate',
                'verbose_name_plural': 'Affiliates',
                'db_table': 'affiliates',
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_id', models.CharField(db_index=True, max_length=50)),
                ('affiliate_encoded_value', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('conversion_id', models.CharField(blank=True, max_length=255)),
                ('to_process', models.BooleanField(db_index=True, default=False)),
                ('to_process_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('is_processed_datetime', models.DateTimeField(blank=True, null=True)),
                ('to_convert', models.BooleanField(db_index=True, default=False)),
                ('to_convert_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_converted', models.BooleanField(db_index=True, default=False)),
                ('is_converted_datetime', models.DateTimeField(blank=True, null=True)),
                ('r1_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('r7_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('user_agent', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('sub1', models.CharField(blank=True, max_length=255)),
                ('sub2', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'clicks',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('completed_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
            },
        ),
    ]
