# Generated by Django 4.2.7 on 2025-10-21 15:32

from django.db import migrations
from django.contrib.auth.models import User
import os


def create_admin_user(apps, schema_editor):
    """Create admin user from environment variables"""
    User = apps.get_model('auth', 'User')
    
    # Get admin credentials from environment
    admin_username = os.getenv('ADMIN_USERNAME', 'admin')
    admin_password = os.getenv('ADMIN_PASSWORD', 'changeme123')
    admin_email = os.getenv('ADMIN_EMAIL', 'admin@example.com')
    
    # Create admin user if it doesn't exist
    if not User.objects.filter(username=admin_username).exists():
        User.objects.create_superuser(
            username=admin_username,
            email=admin_email,
            password=admin_password
        )
        print(f"Created admin user: {admin_username}")


def reverse_create_admin_user(apps, schema_editor):
    """Remove admin user"""
    User = apps.get_model('auth', 'User')
    admin_username = os.getenv('ADMIN_USERNAME', 'admin')
    User.objects.filter(username=admin_username).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('luckyseven', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_create_admin_user),
    ]
