# Generated by Django 4.2.7 on 2025-10-21 15:34

from django.db import migrations
from decimal import Decimal


def create_affiliates(apps, schema_editor):
    """Create affiliate entries"""
    Affiliate = apps.get_model('luckyseven', 'Affiliate')
    
    # 1269
    Affiliate.objects.create(
        affiliate_id='1269',
        affiliate_encoded_value='32L4XJL',
        payout_target=Decimal('150.00'),
        conversion_ratio_target=Decimal('2.2'),
        conversion_ratio_deviance=Decimal('0.4'),
        daily_revenue_deviance=Decimal('0.10'),
        geos=["US", "UK", "DE", "FR", "CA", "BR", "ES", "PL", "BE", "CH"],
        sub1_type_generate='lambda: str(random.randint(100000, 999999))',
        sub2_type_generate='lambda: "".join(random.choices(string.ascii_lowercase + string.digits, k=32))'
    )
    
    # 5010
    Affiliate.objects.create(
        affiliate_id='5010',
        affiliate_encoded_value='94FMLPM',
        payout_target=Decimal('500.00'),
        conversion_ratio_target=Decimal('2.1'),
        conversion_ratio_deviance=Decimal('0.3'),
        daily_revenue_deviance=Decimal('0.15'),
        geos=["US", "UK", "DE", "FR", "CA", "BR", "ES"],
        sub1_type_generate='lambda: str(uuid.uuid4())',
        sub2_type_generate='lambda: "".join(random.choices(string.ascii_lowercase + string.digits, k=20))'
    )
    
    # 118
    Affiliate.objects.create(
        affiliate_id='118',
        affiliate_encoded_value='6C11D3',
        payout_target=Decimal('450.00'),
        conversion_ratio_target=Decimal('1.5'),
        conversion_ratio_deviance=Decimal('0.3'),
        daily_revenue_deviance=Decimal('0.20'),
        geos=["US", "UK", "DE", "FR", "CA", "BR", "ES"],
        sub1_type_generate='lambda: str(uuid.uuid4())',
        sub2_type_generate='lambda: "".join(random.choices(string.ascii_lowercase + string.digits, k=16))'
    )
    
    # 735
    Affiliate.objects.create(
        affiliate_id='735',
        affiliate_encoded_value='26CB3X8',
        payout_target=Decimal('200.00'),
        conversion_ratio_target=Decimal('1.8'),
        conversion_ratio_deviance=Decimal('0.3'),
        daily_revenue_deviance=Decimal('0.10'),
        geos=["US", "UK", "DE", "FR", "CA", "BR", "ES"],
        sub1_type_generate='lambda: str(random.randint(100000, 999999))',
        sub2_type_generate='lambda: "".join(random.choices(string.ascii_lowercase + string.digits, k=32))'
    )
    
    # 5036
    Affiliate.objects.create(
        affiliate_id='5036',
        affiliate_encoded_value='95LP2N9',
        payout_target=Decimal('200.00'),
        conversion_ratio_target=Decimal('2.3'),
        conversion_ratio_deviance=Decimal('0.3'),
        daily_revenue_deviance=Decimal('0.10'),
        geos=["US", "UK", "DE", "FR", "CA", "BR", "ES"],
        sub1_type_generate='lambda: str(uuid.uuid4())',
        sub2_type_generate='lambda: "".join(random.choices(string.ascii_lowercase + string.digits, k=32))'
    )
    
    # 5038
    Affiliate.objects.create(
        affiliate_id='5038',
        affiliate_encoded_value='95P87WM',
        payout_target=Decimal('125.00'),
        conversion_ratio_target=Decimal('3.6'),
        conversion_ratio_deviance=Decimal('0.3'),
        daily_revenue_deviance=Decimal('0.15'),
        geos=["US", "UK", "DE", "FR", "CA", "BR", "ES", "BE", "AT", "RU", "AU", "CZ"],
        sub1_type_generate='lambda: str(random.randint(10000, 99999))',
        sub2_type_generate='lambda: str(uuid.uuid4())'
    )
    
    # 5058
    Affiliate.objects.create(
        affiliate_id='5058',
        affiliate_encoded_value='96LN467',
        payout_target=Decimal('125.00'),
        conversion_ratio_target=Decimal('2.5'),
        conversion_ratio_deviance=Decimal('0.4'),
        daily_revenue_deviance=Decimal('0.15'),
        geos=["US", "DE", "CA", "BR", "BE", "AT", "CH", "AU", "CZ"],
        sub1_type_generate='lambda: "".join(random.choices(string.ascii_lowercase + string.digits, k=32))',
        sub2_type_generate='lambda: str(uuid.uuid4())'
    )


def reverse_create_affiliates(apps, schema_editor):
    """Remove affiliate entries"""
    Affiliate = apps.get_model('luckyseven', 'Affiliate')
    Affiliate.objects.filter(affiliate_id__in=['1269', '5010', '118', '735', '5036', '5038', '5058']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('luckyseven', '0002_auto_20251021_1132'),
    ]

    operations = [
        migrations.RunPython(create_affiliates, reverse_create_affiliates),
    ]
