# Generated by Django 4.2.7 on 2025-10-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyseven', '0003_auto_20251021_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
